
#More complex example - NOT needed for the immediate test
 name: Caller Workflow
 on: [workflow_dispatch]
 jobs:
   call_the_reusable_workflow:
     runs-on: ubuntu-latest
     steps:
       - name: Step before calling reusable
         run: echo "I am a step in Repo A before calling."
       - name: Call Reusable Workflow
         uses: richard-user01-testing/repo-b-reusable/.github/workflows/reusable-workflow.yml@main
         with:
           caller_name: 'Repo A Caller Workflow'
       - name: Step after calling reusable
       run: echo "I am a step in Repo A after calling."

    
